export default {
  SET_EOS: 'SET_EOS',
  SET_EOS_ACCOUNT: 'SET_EOS_ACCOUNT',
  SCATTER_INIT: 'SCATTER_INIT',
  SCATTER_LOGIN: 'SCATTER_LOGIN',
  SCATTER_LOGOUT: 'SCATTER_LOGOUT',
  SET_IS_BP: 'SET_IS_BP',
  SET_IS_SCATTER_LOGIN_LOADING: 'SET_IS_SCATTER_LOGIN_LOADING',
  SET_IS_SCATTER_NOT_CONNECTED: 'SET_IS_SCATTER_NOT_CONNECTED',
  SET_ROUTE_TO: 'SET_ROUTE_TO',
  DEFINE_ROUTE_TO: 'DEFINE_ROUTE_TO',
};
