export default {
  SET_EOS: 'SET_EOS',
  SET_EOS_ACCOUNT: 'SET_EOS_ACCOUNT',
  SCATTER_INIT: 'SCATTER_INIT',
  SCATTER_LOGOUT: 'SCATTER_LOGOUT',
  SET_IS_BP: 'SET_IS_BP',
  SET_IS_SCATTER_INIT_LOADING: 'SET_IS_SCATTER_INIT_LOADING',
  SET_IS_SCATTER_NOT_CONNECTED: 'SET_IS_SCATTER_NOT_CONNECTED',
};
